# Generated by Django 5.1.7 on 2025-03-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_token_student_address_student_accommodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='accommodation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Yashash joyi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_form',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Ta'lim shakli"),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Ta'lim turi"),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name="To'liq ismi"),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Guruh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasport raqami'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_pin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasport PIN'),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_form',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="To'lov shakli"),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Semestr'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mutaxassislik'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Talaba ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Universitet'),
        ),
    ]
