# Generated by Django 5.1.7 on 2025-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(verbose_name='Baho'),
        ),
    ]
