# Generated by Django 5.1.7 on 2025-03-25 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_grade_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.CreateModel(
            name='AcademicDebt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('subject', models.CharField(max_length=200, verbose_name='Fan')),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qarz summasi')),
                ('retake_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', 'To‘langan'), ('retaken', 'Qayta topshirilgan')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Talaba')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('service_type', models.CharField(choices=[('contract_payment', 'To‘lov-shartnoma'), ('scholarship_order', 'Stipendiya tayinlash'), ('retake_payment', 'Qayta o‘qish to‘lovi'), ('subsidy_application', 'Ijara subsidiyasi'), ('employment_info', 'Ishga joylashish ma’lumotlari')], max_length=200, verbose_name='Xizmat turi')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Summa')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='So‘rov sanasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan')], default='pending', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Talaba')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('service_type', models.CharField(choices=[('reference_letter', 'Ingliz tilida ma’lumotnoma'), ('mobility_program', 'Akademik mobillik dasturi'), ('visa_service', 'Viza xizmatlari'), ('foreign_admission', 'Xorijda o‘qishga qabul')], max_length=200, verbose_name='Xizmat turi')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='So‘rov sanasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan')], default='pending', max_length=50)),
                ('response', models.TextField(blank=True, null=True, verbose_name='Javob')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Talaba')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('service_type', models.CharField(choices=[('grant_info', 'Grantlar haqida ma’lumot'), ('conference_info', 'Ilmiy konferensiyalar'), ('startup_registration', 'Startap ro‘yxati'), ('scholarship_application', 'Nomdor stipendiya'), ('project_consultation', 'Ilmiy loyiha konsultatsiyasi')], max_length=200, verbose_name='Xizmat turi')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='So‘rov sanasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan')], default='pending', max_length=50)),
                ('details', models.TextField(blank=True, null=True, verbose_name='Tafsilotlar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Talaba')),
            ],
        ),
        migrations.CreateModel(
            name='StudentService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('request_type', models.CharField(choices=[('schedule', 'Dars jadvali'), ('retake_application', 'Qayta o‘qish uchun ariza'), ('exam_list', 'Imtihonlar ro‘yxati'), ('transcript', 'Transkript'), ('certificate', 'Talaba guvohnomasi'), ('gpa_info', 'GPA ma’lumotnoma'), ('password_reset', 'Parolni tiklash'), ('medical_insurance', 'Tibbiy sug‘urta'), ('transfer_application', 'O‘qishni ko‘chirish'), ('subsidy_application', 'Ijara subsidiyasi'), ('dorm_application', 'Yotoqxonaga ariza')], max_length=200, verbose_name='So‘rov turi')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='So‘rov sanasi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan')], default='pending', max_length=50)),
                ('response', models.TextField(blank=True, null=True, verbose_name='Javob')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Talaba')),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
